services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_USER: userdba
      POSTGRES_DB: test-db
    networks:
      - sandbox

volumes:
  pgdata:
networks:
  sandbox:
    driver: bridge
